//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWCFService.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverDetail
    {
        public DriverDetail()
        {
            this.ETDDetails = new HashSet<ETDDetail>();
        }
    
        public int driver_id { get; set; }
        public string driver_name { get; set; }
    
        public virtual ICollection<ETDDetail> ETDDetails { get; set; }
    }
}
